### ISSUE TITLE
macOS Sierra + Alfred 3 issues

### ISSUE THREAD

**Issue by claytongray** [dv/alfred-omnifocus-workflow#3]
For macOS Sierra, make sure to install 'appscript', as mentioned in another thread. I could not get this workflow to work on my machine without it.

`sudo gem install rb-appscript`

**Comment by zwpaper** [comment]
life saver! this should really add to the Readme!

**Comment by lidaobing** [comment]
```
$ sudo gem install rb-appscript
Fetching: rb-appscript-0.6.1.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing rb-appscript:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.5.0/gems/rb-appscript-0.6.1
/usr/local/opt/ruby/bin/ruby -r ./siteconf20180305-74820-1sopcm8.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.5.0_2/bin/$(RUBY_BASE_NAME)
extconf.rb:44:in `<main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.5.0/gems/rb-appscript-0.6.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0/rb-appscript-0.6.1/gem_make.out
```

**Comment by iT-Boyer** [comment]
> ```
> $ sudo gem install rb-appscript
> Fetching: rb-appscript-0.6.1.gem (100%)
> Building native extensions. This could take a while...
> ERROR:  Error installing rb-appscript:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /usr/local/lib/ruby/gems/2.5.0/gems/rb-appscript-0.6.1
> /usr/local/opt/ruby/bin/ruby -r ./siteconf20180305-74820-1sopcm8.rb extconf.rb
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/usr/local/Cellar/ruby/2.5.0_2/bin/$(RUBY_BASE_NAME)
> extconf.rb:44:in `<main>': uninitialized constant Config (NameError)
> Did you mean?  RbConfig
>                CONFIG
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /usr/local/lib/ruby/gems/2.5.0/gems/rb-appscript-0.6.1 for inspection.
> Results logged to /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0/rb-appscript-0.6.1/gem_make.out
> ```

I encountered the same problem during installation。
