### ISSUE TITLE
error  ERROR: Failed to build gem native extension.  use Alfred4

### ISSUE THREAD

**Issue by iT-Boyer** [dv/alfred-omnifocus-workflow#5]
gem pristine ffi --version 1.12.2
gem pristine sassc --version 2.3.0
gem pristine unf_ext --version 0.0.7.6
gem pristine redcarpet --version 3.5.0
```
15:48:50.535] Omnifocus Create[Script Filter] Queuing argument 'j'
[15:48:50.724] Omnifocus Create[Script Filter] Script with argv '(null)' finished
[15:48:50.739] ERROR: Omnifocus Create[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./main.rb:9:in `<main>'
```

**Comment by iT-Boyer** [comment]
`sudo gem install rb-appscript`

```
Building native extensions. This could take a while...
ERROR:  Error installing rb-appscript:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/rb-appscript-0.6.1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201125-15532-1e59fo5.rb extconf.rb

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
extconf.rb:44:in `<main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/rb-appscript-0.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/rb-appscript-0.6.1/gem_make.out
```
